# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Using previous working client_id temporarily
client_id = "5810fe1357c5113bec8e8dec0ed9e374"
name = "poc-v2"
application_url = "https://shopify-poc.pages.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shopify-poc.pages.dev/api/auth", "https://shopify-poc.pages.dev/auth/shopify/callback" ]
