#:schema node_modules/wrangler/config-schema.json
name = "shopify-poc"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"

[vars]
# Secrets are now managed via wrangler pages secret put

[[d1_databases]]
binding = "DB"
database_name = "shopify_poc"
database_id = "1b84d358-7ace-4349-95ea-d8075b61a6a4"

[env.production]
name = "shopify-poc"

[env.production.vars]
NODE_ENV = "production"
# Secrets are now managed via wrangler pages secret put

[[env.production.d1_databases]]
binding = "DB"
database_name = "shopify_poc"
database_id = "1b84d358-7ace-4349-95ea-d8075b61a6a4"

[observability]
enabled = true
