#:schema node_modules/wrangler/config-schema.json
name = "shopify-poc"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"

[env.production]
name = "shopify-poc"

[env.production.vars]
NODE_ENV = "production"

[observability]
enabled = true